# Generated by Django 5.1.2 on 2024-11-02 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="biography",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="movies.category",
            ),
        ),
    ]
