# Generated by Django 5.1.2 on 2024-11-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_actor_biography_movie_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="birthday",
            field=models.DateField(null=True, verbose_name="Birthday"),
        ),
        migrations.AlterField(
            model_name="director",
            name="birthday",
            field=models.DateField(null=True, verbose_name="Birthday"),
        ),
    ]
