# Generated by Django 5.1.2 on 2024-11-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_director_biography"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="screenshot1",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/screenshots"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="screenshot2",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/screenshots"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="screenshot3",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/screenshots"
            ),
        ),
        migrations.AlterField(
            model_name="actor",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="images/actors"),
        ),
        migrations.AlterField(
            model_name="director",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/directors"
            ),
        ),
        migrations.RemoveField(
            model_name="movie",
            name="director",
        ),
        migrations.AlterField(
            model_name="movie",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="images/movies"),
        ),
        migrations.AddField(
            model_name="movie",
            name="director",
            field=models.ManyToManyField(
                null=True, related_name="movies", to="movies.director"
            ),
        ),
    ]
